accounts/urls.py
from django.urls import path
from accounts.views import user_login, user_signup, user_logout

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("signup/", user_signup, name="signup"),
]

projects/urls.py
from django.urls import include, path
from accounts.views import user_login
from projects.views import show_project, list_projects, login, create_project
from . import views

app_name = "projects"

urlpatterns = [
    path("projects/", show_project, name="show_project"),
    path("", projects_list, name="list_projects"),
    path("login/", user_login, name="login"),
    path("accounts/", include("accounts.urls")),
    path("<int:id>/", views.show_project, name="show_project"),
    path("create/", views.create_project, name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import create_task
from .views import show_my_tasks

app_name = "tasks"

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from projects import views


def redirect_to_projects(request):
    return redirect("projects")


urlpatterns = [
    path("", redirect_to_projects, name="home"),
    path("admin/", admin.site.urls),
    path("", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("projects/", views.projects_list, name="projects"),
]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User, related_name="projects", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return self.name


# Create your models here.

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User


# Create your models here.
# class Project(models.Model):


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )
    assignee = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="tasks"
    )

accounts/forms.py
from django import forms


class LogInForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput(),
    )


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput(),
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput(),
    )

projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description"]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = [
            "is_completed",
            "owner",
        ]  # Exclude is_completed and owner fields from the form

accounts/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from accounts.forms import SignUpForm, LogInForm


def user_login(request):
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LogInForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("login")


def user_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]
            first_name = form.cleaned.data["first_name"]
            last_name = form.cleaned_data["last_name"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username,
                    password=password,
                    first_name=first_name,
                    last_name=last_name,
                )
                login(request, user)

                return redirect("home")
            else:
                form.add_error("password", "the passwords do not match")
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Project
from .forms import ProjectForm


@login_required
def projects_list(request):
    projects = Project.objects.filter(owner=request.user)
    context = {"projects": projects}
    return render(request, "projects/list.html", context)


@login_required
def show_project(request):
    projects = Project.objects.all()
    context = {
        "projects": projects,
    }
    return render(request, "projects/detail.html", context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    tasks = project.tasks.all()
    return render(
        request,
        "project_detail.html",
        {"project": project, "tasks": tasks},
    )


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.save()
            return redirect("projects:project_list")
    else:
        form = ProjectForm()
    return render(request, "projects/create_project.html", {"form": form})


def project_list_view(request):
    project_list = Project.objects.all()
    context = {"project_list": project_list}
    pass

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from tasks.forms import TaskForm
from .forms import TaskForm
from .models import Task


def some_view_function(request):
    # Do some stuff
    form = PostForm()
    context = {
        # Other data to put in the template
        "form": form,
    }
    return render(request, "dir/template.html", context)


# Create your views here.


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(
                "project_list"
            )  # Replace 'project_list' with your project list URL name
    else:
        form = TaskForm()

    return render(request, "tasks/create_task.html", {"form": form})


@login_required
def show_my_tasks(request):
    tasks = Task.objects.filter(assignee=request.user)
    return render(request, "tasks/show_my_tasks.html", {"tasks": tasks})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Your Website</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'tasks:show_my_tasks' %}">My tasks</a></li>
                    <li><a href="{% url 'projects:list_projects' %}">My projects</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Login</h1>
        <form method="post">
          {% csrf_token %}
          {{ form }}
          <button type="submit">Login</button>
        </form>
    </div>
  </main>
{% endblock content %}

projects/templates/projects/create_project.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>My Projects</title>
</head>
<body>
    <header>
        <!-- Fundamental Five -->
        <nav>
            <!-- Navigation links -->
        </nav>
    </header>
    <main>
        <div>
            <h1>My Projects</h1>
            {% if projects %}
            <p>
                <a href="{% url 'projects:create_project' %}">Create a new project</a>
            </p>
            
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>{{ project.name }}</td>
                                <td></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects.</p>
            {% endif %}
        </div>
    </main>
</body>
</html>

projects/templates/projects/project_detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>{{ project.projects_list }}</h1>
        <p>{{ project.description }}</p>
        <h2>Tasks</h2>
        <h3>Project Details</h3>
<p><a href="{% url 'tasks:create_task' %}">Create a new task</a></p>

        {% if tasks %}
        <table>
            <tr>
                <th>Name</th>
                <th>Assignee</th>
                <th>Start date</th>
                <th>Due date</th>
                <th>Is completed</th>
            </tr>
            {% for task in tasks %}
            <tr>
                <td>{{ task.projects_list }}</td>
                <td>{{ task.assignee.username }}</td>
                <td>{{ task.start_date }}</td>
                <td>{{ task.due_date }}</td>
                <td>{{ task.is_completed|yesno:"yes,no" }}</td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <p>This project has no tasks.</p>
        {% endif %}
    </div>
</main>
{% endblock %}